### PR TITLE
Final counter check

### PR DESCRIPTION
**Pull request by msettles**
final check, fixed some header defs, added record parameter to phix-remover, that records matches but writes out all reads, added read length histograms to stats, and finally version bump. This completes the slack comments

### CODE REVIEW

**Comment by joe-angell** [comment]
Is this pr the same as #112 ?  I"m a bit confused.

**Comment by msettles** [comment]
No, keeping to the one thing per branch #112 was a reorg of the all the counters and adding in PE/SE  split. This branch was about redoing the adapter trimmer based on this section
8) For adapter trimmer -- move it to being more of a real adapter trimmer only.
   -make error correction an option that can be toggled.
Done earlier
   -modify adapter-trimmer to output only # reads trimmed
Done in #113 
   -modify adapter-trimmer to output sum of bp trimmed
Done in #113 
   -remove the histogram data.
Done in #113 
   -need to support single
Feature request

**Comment by msettles** [comment]
Sorry our correct, I branched off the previous branch, will close #112

**Comment by dstreett** [comment]
It looks good - there are some small things (bools should be used versus ints) but nothing stopping the merge. Feel free to merge in whenever.

**Pull request merged**
